### ISSUE TITLE
Page needs refactoring, working on it

### ISSUE THREAD

**Issue by dr-nefardio3058** [jge162/jge162.github.io#2]
**I've seen that the page can be upgraded and it's very messy in terms of files, names and code in general.** 

I will be working on #1 to solve as much problems and improve this page.

If you can give me your opinion, it is worth a lot to me. 

See you! :shipit: 

Edit: #1 is ready for review!

**Comment by jge162** [comment]
Thanks for all the input, and it is all greatly appreciated. I honestly have not had time to update this repo because of school and job hunting. So I will review your suggestions very closely. Thanks...:) @dr-nefardio3058

**Comment by dr-nefardio3058** [comment]
### Hi Jerememy, 

**I think i will divide the process in maybe 2 or 3 PR'S:**

- One for refactoring and reorganizing stuff (working on it)
- Other focused on the current page
- Upgrading the page

I think it is a best idea because a big PR can be difficult to review, specially with so many changes. Let me know your thoughts.

**Comment by jge162** [comment]
I will review the PR today. thanks again for your time.

**Comment by jge162** [comment]
Thank you for opening issue and the changes. I don’t plan on maintaining this repo. It’s just an example for others to use if they want or don’t. Thanks.

**Comment by dr-nefardio3058** [comment]
I understand! Thanks for reviewing it :shipit:
